version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
skip_commits:
  files:
  - docs/*
  - .gitattributes
  - .gitignore
  - .travis.yml
  - README.md
image:
- Visual Studio 2015
- Ubuntu1804
install:
- sh: >-
    sudo apt update

    sudo apt install --yes nsis
build_script:
- cmd: makensis.exe /V3 bdelock.nsi
- sh: makensis -V3 bdelock.nsi
test: off
deploy: off
