language: minimal
sudo: false

notifications:
  email: false
  irc: false

os: linux
dist: xenial

branches:
  only: master

addons:
  apt:
    update: true
    packages: nsis

install: true

script: makensis -V3 bdelock.nsi
