language: minimal
sudo: false

notifications:
  email:
    on_success: never

branches:
  only: master

matrix:
  allow_failures:
  - os: windows
    install: choco install nsis -y
    script: makensis.exe /V3 bdelock.nsi
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        update: true
        packages: nsis
    install: true
    script: makensis -V3 bdelock.nsi
