language: minimal
sudo: false

notifications:
  email:
    on_success: never

branches:
  only: master

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(^\.(git|appveyor))|(^(LICENSE|docs))'
    then
      echo "Only build non-relevant files were updated, not running the CI."
      exit
    fi

matrix:
  allow_failures:
  - os: windows
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        update: true
        packages: nsis
    install: true
    script: makensis -V3 bdelock.nsi
  - os: windows
    filter_secrets: false
    install: choco install nsis -y
    script: makensis.exe /V3 bdelock.nsi
