version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image:
- Visual Studio 2015
- Ubuntu1804
install:
- sh: >-
    sudo apt update

    apt-cache policy nsis

    sudo apt install --yes nsis
build_script:
- cmd: makensis.exe /V3 bdelock.nsi
- sh: cat bdelock.nsi && makensis bdelock.nsi -V4
test: off
deploy: off
