theme: minima
title: bde-lock - project documentation
description: a simple Windows installer for a drive context menu function to lock an unlocked BitLocker encrypted drive in Windows
author: Daniel Leidert
email: daniel.leidert@wgdd.de
lang: en
show_downloads: true
show_excerpts: true
google_analytics:
paginate: 6

header_pages:
  - about.md
  - posts.md
  - changelog.md
  - translation.md

social:
  name: Daniel Leidert
  links:
    - https://github.com/dleidert/
    - https://instagram.com/daniel.leidert/

# minima >2.5.0 (current master)
minima:
  social_links:
    github: dleidert
    instagram: daniel.leidert
    rss: rss

# minima 2.5.0
github_username: dleidert
instagram_username: daniel.leidert
rss: rss

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
