theme: jekyll-theme-minimal
title: bde-lock - simple Windows installer for a drive context menu function to lock an unlocked BitLocker encrypted drive
description: official documentation about the bde-lock project
