theme: minima
title: bde-lock - project documentation
description: a simple Windows installer for a drive context menu function to lock an unlocked BitLocker encrypted drive in Windows
author: Daniel Leidert
email: daniel.leidert@wgdd.de
lang: en
show_downloads: true
show_excerpts: true
google_analytics:
google_site_verification: gPitPikijaA6VSAckqTh85FsSKzUU0kuVRIRpLqNA08
paginate: 6
paginate_path: "/page/:num/"
excerpt_separator: <!-- excerpt -->

header_pages:
  - index.md
  - posts.md
  - changelog.md
  - translation.md

#seo:
#  type: SoftwareApplication
#  links:
#    - https://github.com/dleidert/

#social:
#  name: Daniel Leidert
#  links:
#    - https://github.com/dleidert/
#    - https://instagram.com/daniel.leidert/
#    - https://salsa.debian.org/dleidert
#    - https://www.xing.com/profile/Daniel_Leidert
#    - https://m.youtube.com/channel/UCcByb2fCTx7B8QwZBdGxDgA

# minima >2.5.0 (current master)
minima:
  social_links:
    github: dleidert
    instagram: daniel.leidert
    youtube_channel: UCcByb2fCTx7B8QwZBdGxDgA
    xing: Daniel_Leidert
    debian: dleidert
    rss: rss

# minima 2.5.0
github_username: dleidert
instagram_username: daniel.leidert
youtube_username: UCcByb2fCTx7B8QwZBdGxDgA
xing_username: Daniel_Leidert
debian_username: dleidert
rss: rss

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
